### PR TITLE
Create ML pipeline notebook & Add test data to data/

### PR DESCRIPTION
**Pull request by PhilsChan**
@sukhleen999 I have basically done the ML pipeline, please feel free to add any data visualization on top of the notebook.
@nd265 @Affrin101 Please also check if there is any logic flaw or problem.
Note: the model_building.ipynb is only for ease of development, a `model_building.py` script will be created later to produce table and graph as seperate artifacts

### CODE REVIEW

**Comment by sukhleen999** [comment]
Hey team, I was wondering if we should use f1 score for hyperparameter optimization since the target column has class imbalance and therefore accuracy would not be a good choice. Let me know your thoughts on this.

**Comment by PhilsChan** [comment]
> Hey team, I was wondering if we should use f1 score for hyperparameter optimization since the target column has class imbalance and therefore accuracy would not be a good choice. Let me know your thoughts on this.

I was not quite sure on this issue since I think both classes in this dataset have equal importance, so we might not want to only take consideration of the positive class, i.e. >50K.
However, I think the tuning the threshold value is also boosting the F1 score and sacrificing the accuracy. So maybe turning to optimize F1 solely would make the pipeline more consistent.

**Comment by Affrin101** [comment]
Yes, even I feel accuracy would not be a good choice for hyperparameter optimization

**Review by nd265 — APPROVED** [review]
It's correct as per what we discussed and stands to our expectations! Thanks @PhilsChan

**Comment by nd265** [comment]
> > Hey team, I was wondering if we should use f1 score for hyperparameter optimization since the target column has class imbalance and therefore accuracy would not be a good choice. Let me know your thoughts on this.
> 
> I was not quite sure on this issue since I think both classes in this dataset have equal importance, so we might not want to only take consideration of the positive class, i.e. >50K. However, I think the tuning the threshold value is also boosting the F1 score and sacrificing the accuracy. So maybe turning to optimize F1 solely would make the pipeline more consistent.

I agree with @sukhleen999 , although the importance of both classes is same, but here our objective is to classify them as correctly as possible, so if there is high imbalance, I think model will be biased to the class that is in majority, which will affect our model's ability to generalise the predictions

**Review by Affrin101 — APPROVED** [review]

**Review by sukhleen999 — APPROVED** [review]
Looks good now!

**Pull request merged**
