### PR TITLE
Added some changes in the introduction of Readme

### PR DESCRIPTION
**Pull request by Affrin101**

### CODE REVIEW

**Review by PhilsChan — COMMENTED** [review]
why do you delete matplotlib in the dependency?

**Comment by Affrin101** [comment]
It was added twice, one matplotlib with version is already present in the yaml file

**Comment by PhilsChan** [comment]
> It was added twice, one matplotlib with version is already present in the yaml file

Oh alright

**Review by PhilsChan — APPROVED** [review]

**Review by sukhleen999 — APPROVED** [review]

**Review by nd265 — APPROVED** [review]
very nice introduction

**Pull request merged**
