### PR TITLE
Complete model_building.py & basic structure for report

### PR DESCRIPTION
**Pull request by PhilsChan**
Created report structure, whuch you might find in `doc/`, while the children documents are placed in `doc/child`.

`model_building.py` is basically done, 2 csv files and 1 model pickle file would be produced.

Btw @nd265 I have fixed a minor bug in `clean_data.py` (indentation problem, causing the directory unabled to be created)
Please check if there is any problem.

### CODE REVIEW

**Review by Affrin101 — APPROVED** [review]
@PhilsChan  verified the documents!! Thank you for all the effort.
Just wanted a minor clarification, we are using clean_data.csv, right? do you think in model_building.py  in the options section we can change "Path of raw train file" to "Path of clean train file". I have also added the same in my eda script. Please advise

**Comment by PhilsChan** [comment]
> @PhilsChan verified the documents!! Thank you for all the effort. Just wanted a minor clarification, we are using clean_data.csv, right? do you think in model_building.py in the options section we can change "Path of raw train file" to "Path of clean train file". I have also added the same in my eda script. Please advise

Sure! I just did not pay too much attention on the comment section lmao

**Review by sukhleen999 — APPROVED** [review]
Good catch @Affrin101. Looks good otherwise.

**Review by Affrin101 — COMMENTED** [review]
@PhilsChan  can you also print the best score and best hyperparameters which got selected after tuning to model_building.py?

**Comment by PhilsChan** [comment]
Added the starter code of `model_evaluation.py` for further development

> @PhilsChan can you also print the best score and best hyperparameters which got selected after tuning to model_building.py?

@Affrin101 Actually I exported the result into a csv file, where I will reference it in the final report. I guess the script does not have to print some much information as we will include them in final report.

**Pull request merged**
