### PR TITLE
Additional analysis in EDA.ipynb

### PR DESCRIPTION
**Pull request by sukhleen999**

### CODE REVIEW

**Review by Affrin101 — COMMENTED** [review]
The visualization of categorical columns is quite insightful!! There's a histogram plot of the native country which looks a bit crowded, do you think we should keep that?

**Comment by sukhleen999** [comment]
I agree that it does look crowded, however eliminating it altogether would not be the right approach. To improve the plot, I could add a text to the bar corresponding to US which has the highest count. Let me know what you think.

**Comment by PhilsChan** [comment]
> The visualization of categorical columns is quite insightful!! There's a histogram plot of the native country which looks a bit crowded, do you think we should keep that?

I think we could categorize the data in `native_country` into US and non-US country and then plot another graph to talk about this column.

**Comment by sukhleen999** [comment]
Great idea @PhilsChan , I'll give it a try.

**Pull request merged**
