### PR TITLE
Finishing first draft on my part of report & upload tables and model

### PR DESCRIPTION
**Pull request by PhilsChan**

### CODE REVIEW

**Review by nd265 — APPROVED** [review]
the documentation looks fine to me. I have resolved a few typos in there and some grammar.

**Comment by PhilsChan** [comment]
> the documentation looks fine to me. I have resolved a few typos in there and some grammar.

Thanks a lot!

**Review by Affrin101 — APPROVED** [review]
Reviewed it and added an additional path for EDA script in the README.md file and fixed some typos.

**Comment by PhilsChan** [comment]
Also added the future development part of the report. Please check

**Review by sukhleen999 — APPROVED** [review]
I have reviewed the files. Everything looks good, thanks!

**Pull request merged**
