### PR TITLE
Create Makefile and bug fix

### PR DESCRIPTION
**Pull request by PhilsChan**
Fixed some bugs:
1. Added pandoc in dependency for rendering the html with `Rscript` in conda environment
2. Garbage collection for `train_df_info.csv` in `src/eda_script.py`
3. Fixed a typo in `model_evaluation.py`

### CODE REVIEW

**Review by nd265 — COMMENTED** [review]
All changes are fine, but in the eda_script.py, why do we need to add os.remove(train_info.csv)? because for a person who downloads it for the first time, he won't have train_info.csv and i have added the shutil command that everytime deletes the whole directory and then adds the files in that, i guess you had initially ran the script and this older train_info.csv was there because of that. I suggest you clone the repo again from fresh and try it once. if train_info.csv comes, then we need to see why it is coming, else for people who try to run the script for the first time, it will throw an error saying train_info.csv not found, so we cannot generalise it and add it in the code

**Comment by PhilsChan** [comment]
> All changes are fine, but in the eda_script.py, why do we need to add os.remove(train_info.csv)? because for a person who downloads it for the first time, he won't have train_info.csv and i have added the shutil command that everytime deletes the whole directory and then adds the files in that, i guess you had initially ran the script and this older train_info.csv was there because of that. I suggest you clone the repo again from fresh and try it once. if train_info.csv comes, then we need to see why it is coming, else for people who try to run the script for the first time, it will throw an error saying train_info.csv not found, so we cannot generalise it and add it in the code

What I did is `os.remove("train_df_info.csv")`, which is an intermediate file that you dumped the output of train_df.info(), and read it to create `train_info.csv`. When I rerun the whole stuff after `make clean`, I found this extra file was produced in the root directory and thus I decided to add a line to remove this intermediate product after the actual `results/eda/train_info.csv` is properly saved.

**Review by nd265 — APPROVED** [review]
All good !

**Review by sukhleen999 — APPROVED** [review]

**Review by Affrin101 — APPROVED** [review]
Good catch @PhilsChan ( regarding the garbage file created by eda-script )

**Pull request merged**
