### PR TITLE
Facing issue while running eda_script.py

### PR DESCRIPTION
**Pull request by Affrin101**
Hi Team,
    I have attached the eda_script.py,  for some reason while running the script I am facing an error(error message pasted below) which I am not able to resolve.

[Errno 2] No such file or directory: 'data/preprocessed/clean_train.csv'

  Can you please have a look at it and let me know what the issue is? Also, please advise in case of any modification. I have created a bug and I am assigning it to @nd265.

### CODE REVIEW

**Comment by nd265** [comment]
> Hi Team, I have attached the eda_script.py, for some reason while running the script I am facing an error(error message pasted below) which I am not able to resolve.
> 
> [Errno 2] No such file or directory: 'data/preprocessed/clean_train.csv'
> 
> Can you please have a look at it and let me know what the issue is? Also, please advise in case of any modification. I have created a bug and I am assigning it to @nd265.

Hi @Affrin101 , I will work on it. Thanks for letting me know!!

**Comment by PhilsChan** [comment]
> > Hi Team, I have attached the eda_script.py, for some reason while running the script I am facing an error(error message pasted below) which I am not able to resolve.
> > [Errno 2] No such file or directory: 'data/preprocessed/clean_train.csv'
> > Can you please have a look at it and let me know what the issue is? Also, please advise in case of any modification. I have created a bug and I am assigning it to @nd265.
> 
> Hi @Affrin101 , I will work on it. Thanks for letting me know!!

The bug is due to wrong indentation on line 41-43. And that is fixed in #31

**Review by PhilsChan — APPROVED** [review]
Looks good to me! Nice work!

**Comment by PhilsChan** [comment]
One more thing, regarding the categorical feature, I noticed that you have removed `native_country` due to the class imbalance, would you also include an extra graph to talk about this point? I think we have done that in `EDA.ipynb`. Thanks!

**Comment by Affrin101** [comment]
Yes, there are two more graphs in the EDA.ipynb, but I thought this file would get too crowded with many graphs and figures, and hence I didn't add all of them. If you and other team members feel that it adds value, I can definitely include it in the script.

**Comment by PhilsChan** [comment]
> Yes, there are two more graphs in the EDA.ipynb, but I thought this file would get too crowded with many graphs and figures, and hence I didn't add all of them. If you and other team members feel that it adds value, I can definitely include it in the script.

Since I have done extra transformation to `native_country`, that is I make it into a binary feature due to the serious class imbalance problem, I hope you would explicitly talk about this point in EDA to justify my decision :))

**Comment by nd265** [comment]
> > > Hi Team, I have attached the eda_script.py, for some reason while running the script I am facing an error(error message pasted below) which I am not able to resolve.
> > > [Errno 2] No such file or directory: 'data/preprocessed/clean_train.csv'
> > > Can you please have a look at it and let me know what the issue is? Also, please advise in case of any modification. I have created a bug and I am assigning it to @nd265.
> > 
> > 
> > Hi @Affrin101 , I will work on it. Thanks for letting me know!!
> 
> The bug is due to wrong indentation on line 41-43. And that is fixed in #31

No, the bug is not due to the indentation, it is due to the newline character missing after Usage and Options in the script. I have fixed this issue and there are a few more minor changes that I will do and push tomorrow. Rest , it seems fine!!

**Comment by nd265** [comment]
I found one more issue in this: when you are trying to convert train_df.info() to a csv file, it won't happen, because it returns None and simply prints the summary as a string, so I am writing my own function to convert it to a df, so that it can be stored as an image later. I need some more time to do these major fixes. Thankyou!!

**Comment by nd265** [comment]
what do you guys think about including the df.describe() table vs the box plot of the numeric features? because both of them represent the same information- one in table format and one in plot format. Personally, I feel showing plot will be better here instead of the table for describe() and we can write explanations after interpreting the boxplot of the numeric features. What do you guys suggest? We can show only one of them to avoid redundancy 
image
image

**Comment by Affrin101** [comment]
In my view, including the plot is a better idea!!

**Comment by PhilsChan** [comment]
> In my view, including the plot is a better idea!!

I will vote for the plot as well!

**Comment by nd265** [comment]
Hi Team, I have fixed the issues in Affrin's code for which you can find a n explanation here https://github.com/UBC-MDS/census-income-prediction/pull/34. Kindly let me know your review !! And then we can close this issue.

**Comment by sukhleen999** [comment]
I also feel that plot is rendered better and is more insightful visually!

**Comment by PhilsChan** [comment]
Improved version in #34

**Pull request closed without merging**
