### PR TITLE
Minor fix on final report and pipeline & Create Dockerfile & Update README.md

### PR DESCRIPTION
**Pull request by PhilsChan**
`Makefile`: add dependency on `corr_plot.png`
`02-Datasets.Rmd`: Add caption for correlation plot, and fix the format for captions
`03-Findings.Rmd`: Update the hyperparameter we actually selected, and `class=balanced` does not boost ROC_AUC
`model_building.py`: change the sorting order of the csv to `ROC_AUC`, which is used for reft

### CODE REVIEW

**Comment by PhilsChan** [comment]
Note that for `README.md`, the docker image name is `username/census-income-prediction` for now.
This is subject to change upon the github action part is done.

**Comment by Affrin101** [comment]
@PhilsChan  when I work on the Github actions part, should I create another account in Dockerhub and link the username with it or use my existing docker hub account?

**Review by Affrin101 — APPROVED** [review]
Great work on the DockerFile part!!

**Comment by PhilsChan** [comment]
> @PhilsChan when I work on the Github actions part, should I create another account in Dockerhub and link the username with it or use my existing docker hub account?

I guess both are fine but you could confirm with Florencia or TAs

**Review by nd265 — APPROVED** [review]

**Review by sukhleen999 — APPROVED** [review]

**Pull request merged**
