### PR TITLE
Added summary metrics in model_evaluation script 

### PR DESCRIPTION
**Pull request by sukhleen999**
Hi team, I have added the code to export summary matrices and plots in the model_evaluation.py script. There were a few modifications made so I've updated the model_building.ipynb file to incorporate the changes. Please review and let me know in case of a concern.

### CODE REVIEW

**Review by PhilsChan — COMMENTED** [review]
Line 101 is duplicated 
The AUC score shall not be hard coded, it’s better calculated with sklearn and plug to the graph title
can you also include AP score in the title for PR curve? Or we could just include the AP and AUC score in the metric table as well

**Comment by nd265** [comment]
> Line 101 is duplicated The AUC score shall not be hard coded, it’s better calculated with sklearn and plug to the graph title can you also include AP score in the title for PR curve? Or we could just include the AP and AUC score in the metric table as well

I have fixed a minor typo in one of the comments. Rest looks fine to me, after the changes suggested by Philson are done, we can merge it !!

**Review by nd265 — COMMENTED** [review]
I have fixed a minor typo in one of the comments. Rest looks fine to me, after the changes suggested by @PhilsChan  are done, we can merge it !!. Also, could you push the images and tables to github?

**Comment by sukhleen999** [comment]
@PhilsChan I like the idea of putting both the metrics separately in a table. I'll make that change.
@nd265 pushed the artifacts folder.

**Comment by sukhleen999** [comment]
@PhilsChan @nd265 @Affrin101 I have added a table for scores of the test data. Please review the changes.

**Review by PhilsChan — APPROVED** [review]
Looks good now

**Review by nd265 — APPROVED** [review]

**Review by Affrin101 — APPROVED** [review]

**Pull request merged**
